---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amp-admin-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    - nodes/metrics
    - services
    - endpoints
    - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amp-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: iamproxy-amp
    namespace: prometheus
roleRef:
  kind: ClusterRole
  name: amp-admin-role
  apiGroup: rbac.authorization.k8s.io

---

