apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-fargate-amp
  region: $AWS_REGION
  version: '1.21'
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: iamproxy-amp
      namespace: prometheus
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "aps:RemoteWrite"
        - "aps:GetSeries"
        - "aps:GetLabels"
        - "aps:GetMetricMetadata"
        - "aps:QueryMetrics"
        Resource: '*'
fargateProfiles:
  - name: defaultfp
    selectors:
      - namespace: prometheus
      - namespace: kube-system
      - namespace: default
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
